#ifndef UI_Dashboard_H
#define UI_Dashboard_H

const char* html_dashboard = R"rawliteral(
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<title>Dashboard</title>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&display=swap" rel="stylesheet">
<style>
body { background: #cce5ff; font-family: 'Roboto Mono', monospace; padding: 10px; margin: 0; box-sizing: border-box; }

.grid {
  display: grid; grid-template-columns: 1fr 1fr; gap: 10px;
  max-width: 600px; margin: 0 auto;
}
.card {
  background: white; border-radius: 12px; padding: 15px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
  display: flex; flex-direction: column;
}
.full { grid-column: span 2; }
h3 { margin: 0 0 10px 0; font-size: 0.8rem; color: #555; text-transform: uppercase; }
.val { font-size: 2rem; font-weight: bold; color: #001d32; }

.graph {
  height: 60px; background: #f0f0f0; border-radius: 4px; position: relative; overflow: hidden;
}
.line {
  position: absolute; bottom: 0; left: 0; height: 10px; width: 5px; background: #00639b;
  animation: move 2s linear infinite;
}
@keyframes move { from{left:-10px;} to{left:100%;} }

.btn {
  background: #00639b; color: white; border: none; padding: 15px; border-radius: 8px;
  font-family: inherit; font-size: 1.2rem; cursor: pointer;
}
.btn:active { opacity: 0.8; }
.btn.stop { background: #b3261e; }

</style>
</head>
<body>

<div class="grid">
  <div class="card full">
    <h3>Status</h3>
    <div class="val" id="st">IDLE</div>
  </div>
  
  <div class="card">
    <h3>Time</h3>
    <div class="val" id="time">00s</div>
  </div>
  
  <div class="card">
    <h3>Angle</h3>
    <div class="val" id="ang">0°</div>
  </div>
  
  <div class="card full">
    <h3>Pressure Load</h3>
    <div class="graph" id="graph">
      <!-- Bars generated by JS -->
    </div>
  </div>
  
  <button class="btn full" onclick="tog()" id="btn">INITIATE</button>
  
  <div class="card full">
    <h3>Config</h3>
    <input type="range" style="width:100%">
  </div>
</div>

<script>
let r = false;
let t_val = 0;
let tmr;

function tog() {
  if(r) {
    // STOP
    r = false;
    clearInterval(tmr);
    document.getElementById('st').innerText = "ABORTED";
    document.getElementById('btn').innerText = "INITIATE";
    document.getElementById('btn').classList.remove('stop');
    fetch('/api/stop');
  } else {
    // START
    r = true;
    t_val = 0;
    document.getElementById('st').innerText = "RUNNING";
    document.getElementById('btn').innerText = "TERMINATE";
    document.getElementById('btn').classList.add('stop');
    fetch('/api/start');
    
    tmr = setInterval(() => {
      t_val++;
      document.getElementById('time').innerText = t_val + "s";
      document.getElementById('ang').innerText = (Math.sin(t_val)*45+45).toFixed(0) + "°";
      
      // Add graph bar
      let g = document.getElementById('graph');
      let b = document.createElement('div');
      b.className = 'line';
      b.style.height = Math.random()*100 + "%";
      b.style.left = "100%";
      b.style.animation = "none";
      b.style.transition = "left 2s linear";
      g.appendChild(b);
      setTimeout(() => b.style.left = "-10px", 10);
      setTimeout(() => b.remove(), 2100);
      
      if(t_val > 9) {
        r = false;
        clearInterval(tmr);
        document.getElementById('st').innerText = "COMPLETE";
        document.getElementById('btn').innerText = "RESET";
        document.getElementById('btn').classList.remove('stop');
        if(navigator.vibrate) navigator.vibrate(500);
      }
    }, 500);
  }
}
</script>
</body>
</html>
)rawliteral";

#endif
